use serde::Serialize;
use tracing::{error, info, warn};

/// An alert generated by the validator.
#[derive(Debug, Clone, Serialize)]
pub struct Alert {
    pub chain_id: String,
    pub alert_type: AlertType,
    pub height: u64,
    pub message: String,
    pub timestamp: i64,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum AlertType {
    Alteration,
    Unreachable,
    Recovered,
}

/// Dispatch alerts to configured sinks.
pub struct AlertDispatcher {
    webhook_url: Option<String>,
    http: reqwest::Client,
}

impl AlertDispatcher {
    pub fn new(webhook_url: Option<String>) -> Self {
        AlertDispatcher {
            webhook_url,
            http: reqwest::Client::new(),
        }
    }

    /// Send an alert. Logs it and optionally posts to webhook.
    pub async fn dispatch(&self, alert: &Alert) {
        match alert.alert_type {
            AlertType::Alteration => {
                error!(
                    chain = %alert.chain_id, height = alert.height,
                    "ALTERATION DETECTED: {}", alert.message
                );
            }
            AlertType::Unreachable => {
                warn!(
                    chain = %alert.chain_id,
                    "Recorder unreachable: {}", alert.message
                );
            }
            AlertType::Recovered => {
                info!(
                    chain = %alert.chain_id,
                    "Recorder recovered: {}", alert.message
                );
            }
        }

        if let Some(url) = &self.webhook_url
            && let Err(e) = self.http.post(url).json(alert).send().await
        {
            warn!("webhook dispatch failed: {}", e);
        }
    }
}
